services:
  price-interfaces_composer:
    build:
      dockerfile: Dockerfile
      context: .docker/composer
    container_name: price-interfaces_composer
    restart: no
    working_dir: /app
    volumes:
      - ./:/app
networks:
  default:
    external: true
    name: shared
